# Multi GS Classifier using an SVM

### Attempt to classifier GS events with an SVM

### Labels: 0 = noGS, 1 = GSb , 2 = GSbb

In [3]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
%matplotlib inline

In [7]:
## Get data from sqlite database
import sqlite3
con = sqlite3.connect("output_multigs.sqlite")
cmd = "SELECT * FROM multigs"
df = pd.read_sql(cmd, con)
con.close()

In [9]:
print(df.shape)
df.head(5)

(164656, 13)

,weight,dr_bb,bb_pt,bb_m,jet1_csv,jet1_pt,jet1_eta,jet1_phi,jet2_csv,jet2_pt,jet2_eta,jet2_phi,isgs
0,0.06858696761127683,0.9479326009750366,806.5130004882812,418.96966552734375,0.9702577590942383,469.232177734375,-1.5524343252182007,0.9885238409042358,0.9068260192871094,340.6133728027344,-0.6224997043609619,1.172365665435791,2
1,0.06578271116110015,1.7108181715011597,345.1067199707031,202.3365936279297,0.9938207864761353,47.74022674560547,1.1105867624282837,-1.9025239944458008,0.9583972692489624,346.8064880371094,0.7639458775520325,-0.22719153761863708,2
2,0.06914970577375731,0.8214343786239624,699.7274169921875,307.8039855957031,0.996420681476593,344.1963806152344,0.9815223217010498,-0.8608603477478027,0.9014108180999756,418.0459289550781,1.0343067646026611,-0.041123680770397186,0
3,0.06980452901154369,1.9686483144760132,235.37661743164062,302.44757080078125,0.9870003461837769,153.34735107421875,0.5176519751548767,0.09655076265335083,0.8629279136657715,140.70248413085938,-0.9721882343292236,1.383388876914978,1
4,0.06855918497711726,1.0615509748458862,743.2310180664062,418.84161376953125,0.9076961874961853,374.1112060546875,0.631812334060669,1.5203626155853271,0.8531956076622009,370.0169372558594,-0.425184965133667,1.6185827255249023,0

In [10]:
feats = df.iloc[:,0:12]
y = df.isgs

In [11]:
print(feats.shape)
feats.head(5)

(164656, 12)

,weight,dr_bb,bb_pt,bb_m,jet1_csv,jet1_pt,jet1_eta,jet1_phi,jet2_csv,jet2_pt,jet2_eta,jet2_phi
0,0.06858696761127683,0.9479326009750366,806.5130004882812,418.96966552734375,0.9702577590942383,469.232177734375,-1.5524343252182007,0.9885238409042358,0.9068260192871094,340.6133728027344,-0.6224997043609619,1.172365665435791
1,0.06578271116110015,1.7108181715011597,345.1067199707031,202.3365936279297,0.9938207864761353,47.74022674560547,1.1105867624282837,-1.9025239944458008,0.9583972692489624,346.8064880371094,0.7639458775520325,-0.22719153761863708
2,0.06914970577375731,0.8214343786239624,699.7274169921875,307.8039855957031,0.996420681476593,344.1963806152344,0.9815223217010498,-0.8608603477478027,0.9014108180999756,418.0459289550781,1.0343067646026611,-0.041123680770397186
3,0.06980452901154369,1.9686483144760132,235.37661743164062,302.44757080078125,0.9870003461837769,153.34735107421875,0.5176519751548767,0.09655076265335083,0.8629279136657715,140.70248413085938,-0.9721882343292236,1.383388876914978
4,0.06855918497711726,1.0615509748458862,743.2310180664062,418.84161376953125,0.9076961874961853,374.1112060546875,0.631812334060669,1.5203626155853271,0.8531956076622009,370.0169372558594,-0.425184965133667,1.6185827255249023

In [12]:
print(y.shape)
y.head(5)

(164656,)

0    2
1    2
2    0
3    1
4    0
Name: isgs, dtype: object